server:
  port: 8081

tool:
  endpoint: http://localhost:8081/agent/task
  name: Java Agentic AI Developer
  intents:
    - codeAssist
    - refactorCode
    - debugCode
    - microservice
  description: Expert Java developer assistant

mcp:
  server:
    url: ws://localhost:8080/mcp
